sudo: required
services:
  - docker 

before_install:
  - docker build -t abdulsaid/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true abdulsaid/docker-react npm run test

deploy:
  provider: elasticbeanstalk 
  region: "us-east-1"
  app: "docker-react-app"
  env: "Docker-react-app-env"
  bucket_name: "elasticbeanstalk-us-east-1-465524792626"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
